In [1]:
mylist = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.random.rand(5,5)

array([[0.37611508, 0.23213924, 0.40990595, 0.50665921, 0.90249789],
       [0.14523334, 0.76093906, 0.19013281, 0.95890024, 0.18597563],
       [0.74361985, 0.49046805, 0.48302528, 0.75154191, 0.13740678],
       [0.3484271 , 0.09789646, 0.62081828, 0.5334059 , 0.81073194],
       [0.77746576, 0.93589106, 0.07407217, 0.33636107, 0.98752287]])

In [10]:
np.random.randn(5,5)

array([[-0.63993542, -0.6580599 , -0.88556823,  1.75682735, -0.6472523 ],
       [-0.43942086, -0.23521309, -0.79340156, -1.38326614, -1.00210619],
       [ 0.30071893,  0.81165372,  1.4913445 , -0.36262997, -0.46086606],
       [ 0.65347039, -0.08893244, -2.00609893, -1.78612279,  0.74032497],
       [-1.23182859,  1.71549249, -0.91244049,  0.52420087, -0.34218106]])

In [11]:
ab = np.random.rand(5,5)

In [12]:
ab

array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43927211, 0.75885437, 0.38952888],
       [0.37905521, 0.53398121, 0.89054882, 0.03913062, 0.31669296]])

In [13]:
ab[0]

array([0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376])

In [14]:
ab[:][0]

array([0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376])

In [15]:
ab[0,:]

array([0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376])

In [16]:
ab[:,0]

array([0.94185108, 0.81754782, 0.61580008, 0.09984818, 0.37905521])

In [17]:
FAWeights = {'Target1':ab,'target2':ab,'target3':ab}

In [19]:
FAWeights['Target1'].shape

(5, 5)

In [22]:
FAWeights = {'Target1':{'feature1':ab,'feature2':ab},'target2':ab,'target3':ab}

In [23]:
FAWeights['Target1']['feature1'].shape

(5, 5)

In [25]:
FAWeights.keys()

dict_keys(['Target1', 'target2', 'target3'])

In [27]:
FAWeights.values()

dict_values([{'feature1': array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43927211, 0.75885437, 0.38952888],
       [0.37905521, 0.53398121, 0.89054882, 0.03913062, 0.31669296]]), 'feature2': array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43927211, 0.75885437, 0.38952888],
       [0.37905521, 0.53398121, 0.89054882, 0.03913062, 0.31669296]])}, array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43927211, 0.75885437, 0.38

In [38]:
FAWeights_save = {}
FAWeights_save['feature'] = ab
FAWeights.items()

dict_items([('Target1', {'feature1': array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43927211, 0.75885437, 0.38952888],
       [0.37905521, 0.53398121, 0.89054882, 0.03913062, 0.31669296]]), 'feature2': array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43927211, 0.75885437, 0.38952888],
       [0.37905521, 0.53398121, 0.89054882, 0.03913062, 0.31669296]])}), ('target2', array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43

In [58]:
#FAWeights_save = {}
#FAWeights_save[0,0][0] = ab

FAWeights_save = [{}]
FAWeights_save[0]['feature'][0] = ab



KeyError: 'feature'

In [39]:
dicts = {}
keys = range(4)
values = ["Hi", "I", "am", "John"]
for i in keys:
        dicts[i] = values[i]
print(dicts)

{0: 'Hi', 1: 'I', 2: 'am', 3: 'John'}


In [52]:
item{i}.attribute1(2,j)
item[i]['attribute1'][2,j]

SyntaxError: invalid syntax (<ipython-input-52-f31b30c8a485>, line 1)

In [77]:
class structtype():
    pass

FAWeights_final = [ structtype() for i in range(4)]
FAWeights_final[0].feature = [ structtype() for i in range(6)]
FAWeights_final[1].feature = [ structtype() for i in range(6)]
FAWeights_final[2].feature = [ structtype() for i in range(6)]
FAWeights_final[3].feature = [ structtype() for i in range(6)]

In [78]:
type(FAWeights_final)

list

In [79]:
FAWeights_final[0].feature

In [80]:
FAWeights_final[0].feature[0] = ab
FAWeights_final[0].feature[1] = ab
FAWeights_final[0].feature[2] = ab
FAWeights_final[0].feature[3] = ab
FAWeights_final[0].feature[4] = ab
FAWeights_final[0].feature[5] = ab


In [81]:
FAWeights_final[0].feature[3]

array([[0.94185108, 0.14030998, 0.38495295, 0.49739339, 0.36584376],
       [0.81754782, 0.36881604, 0.02075626, 0.10570783, 0.93897955],
       [0.61580008, 0.18241347, 0.73636756, 0.16025503, 0.79790764],
       [0.09984818, 0.46095531, 0.43927211, 0.75885437, 0.38952888],
       [0.37905521, 0.53398121, 0.89054882, 0.03913062, 0.31669296]])

In [82]:
type(FAWeights_final[0].feature[3])

numpy.ndarray

In [83]:
qw = FAWeights_final[0].feature[3]
qw.shape

(5, 5)